### ISSUE TITLE
Build Failure on Avoton / DSM 7.0

### ISSUE THREAD

**Issue by lehitoskin** [runfalk/synology-wireguard#135]
**Description**
I am trying to build for the avoton platform on DSM 7.0, but the build fails with the error `'Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root'`

**Steps to reproduce**
Create docker image:
`sudo docker build -t synology-wireguard .` (this runs successfully)
`mkdir artifacts toolkit_tarballs`
`sudo docker run --rm --privileged --env PACKAGE_ARCH=avoton --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk -v $(pwd)/toolkit_tarballs:/toolkit_tarballs synology-wireguard`
and then the output is as follows:
```
WireGuard version:        1.0.20211208
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.4

Cloning into 'pkgscripts-ng'...
[2022-03-07 20:07:50,817] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.0&platform=base
[2022-03-07 20:08:28,221] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.0&platform=avoton
[2022-03-07 20:09:29,184] INFO: tar -xhf /toolkit_tarballs/base_env-7.0.txz -C /build_env/ds.avoton-7.0
[2022-03-07 20:12:09,131] INFO: tar -xhf /toolkit_tarballs/ds.avoton-7.0.env.txz -C /build_env/ds.avoton-7.0
[2022-03-07 20:15:46,235] INFO: tar -xhf /toolkit_tarballs/ds.avoton-7.0.dev.txz -C /build_env/ds.avoton-7.0
[2022-03-07 20:17:35,240] INFO: All task finished.
--2022-03-07 20:17:38--  https://crt.sh/?d=8395
Resolving crt.sh (crt.sh)... 91.199.212.73, 2a0e:ac00:c7:d449::5bc7:d449
Connecting to crt.sh (crt.sh)|91.199.212.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1200 (1.2K) [application/pkix-cert]
Saving to: 'DSTRootCAX3_Extended.crt'

     0K .                                                     100%  185M=0s

2022-03-07 20:17:40 (185 MB/s) - 'DSTRootCAX3_Extended.crt' saved [1200/1200]

============================================================
                   Parse argument result
------------------------------------------------------------
platforms     : avoton
env_section   : default
env_version   : 7.0
dep_level     : 1
parallel_proj : 1
branch        : master
suffix        :
collect       : True
collecter     : True
link          : True
update_link   : False
build         : True
install       : True
only_install  : False
parallel      : 4
build_opt     : -J
install_opt   :
print_log     : True
tee           : True
sdk_ver       : 6.2
package       : WireGuard

Processing [7.0-42176]: avoton
============================================================
              Start to run "Traverse project"
------------------------------------------------------------
Projects: WireGuard

============================================================
                Start to run "Link Project"
------------------------------------------------------------
Link /pkgscripts-ng -> /build_env/ds.avoton-7.0/pkgscripts-ng
Link //source/WireGuard -> /build_env/ds.avoton-7.0/source/WireGuard


============================================================
                Start to run "Build Package"
------------------------------------------------------------
[avoton] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "/pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "/pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "/pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "/pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "/pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "/pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "/pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "/pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "/pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "/pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "/pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.8/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.avoton-7.0/logs.install: No such file or directory
```

**Comment by sebastianseidel** [comment]
Same here on DSM 7.1-42661 Update 1
`root@NAS:/volume1/projects/wireguard/build/synology-wireguard-master# sudo docker run --rm --privileged --env PACKAGE_ARCH=avoton --env DSM_VER=7.0 -v $(pwd):/result_spk -v /volume1/projects/wireguard/build/toolkit_tarballs:/toolkit_tarballs synobuild
WireGuard version:        1.0.20220627
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.5

Cloning into 'pkgscripts-ng'...
[2022-07-10 16:27:03,728] INFO: tar -xhf /toolkit_tarballs/base_env-7.0.txz -C /build_env/ds.avoton-7.0
[2022-07-10 16:30:36,674] INFO: tar -xhf /toolkit_tarballs/ds.avoton-7.0.env.txz -C /build_env/ds.avoton-7.0
[2022-07-10 16:31:54,011] INFO: tar -xhf /toolkit_tarballs/ds.avoton-7.0.dev.txz -C /build_env/ds.avoton-7.0
[2022-07-10 16:33:00,040] INFO: All task finished.
--2022-07-10 16:33:01--  https://crt.sh/?d=8395
Resolving crt.sh (crt.sh)... 91.199.212.73, 2a0e:ac00:c7:d449::5bc7:d449
Connecting to crt.sh (crt.sh)|91.199.212.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1200 (1.2K) [application/pkix-cert]
Saving to: 'DSTRootCAX3_Extended.crt'

     0K .                                                     100%  397M=0s

2022-07-10 16:33:03 (397 MB/s) - 'DSTRootCAX3_Extended.crt' saved [1200/1200]

============================================================
                   Parse argument result                    
------------------------------------------------------------
platforms     : avoton
env_section   : default
env_version   : 7.0
dep_level     : 1
parallel_proj : 1
branch        : master
suffix        : 
collect       : True
collecter     : True
link          : True
update_link   : False
build         : True
install       : True
only_install  : False
parallel      : 4
build_opt     : -J
install_opt   : 
print_log     : True
tee           : True
sdk_ver       : 6.2
package       : WireGuard

Processing [7.0-42176]: avoton
============================================================
              Start to run "Traverse project"               
------------------------------------------------------------
Projects: WireGuard

============================================================
                Start to run "Link Project"                 
------------------------------------------------------------
Link /pkgscripts-ng -> /build_env/ds.avoton-7.0/pkgscripts-ng
Link //source/WireGuard -> /build_env/ds.avoton-7.0/source/WireGuard


============================================================
                Start to run "Build Package"                
------------------------------------------------------------
[avoton] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check:
 line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check:
 line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "//pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "//pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.avoton-7.0 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --avoton -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check:
 line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.avoton-7.0/logs.install: No such file or directory`
