### ISSUE TITLE
DS415+ (Avoton) DSM 7.0 build fails

### ISSUE THREAD

**Issue by jasperweiss** [runfalk/synology-wireguard#145]
The build script seems to be broken unfortunately.

```
sudo docker run --rm --privileged --env PACKAGE_ARCH=avoton --env DSM_VER=7.0 -v $(pwd)/artifacts:/result_spk -v $(pwd)/tarballs:/toolkit_tarballs synobuild

WireGuard version:        1.0.20211208
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.5

Cloning into 'pkgscripts-ng'...
[2022-05-01 14:37:37,993] INFO: tar -xhf /toolkit_tarballs/base_env-7.0.txz -C /build_env/ds.avoton-7.0
tar (child): xz: Cannot exec: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Traceback (most recent call last):
  File "//pkgscripts-ng/EnvDeploy", line 77, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/EnvDeploy", line 71, in main
    toolkit.deploy()
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 201, in deploy
    self.deploy_base_env(platform)
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 242, in deploy_base_env
    self.__extract__(
  File "/pkgscripts-ng/include/python/pkgdeploy.py", line 239, in __extract__
    subprocess.check_call(cmd)
  File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-7.0.txz', '-C', '/build_env/ds.avoton-7.0']' returned non-zero exit status 2.
```

**Comment by digitalface** [comment]
See https://github.com/runfalk/synology-wireguard/issues/144#issuecomment-1113245293

**Comment by jasperweiss** [comment]
@digitalface #146 fixed this for me
