### ISSUE TITLE
Build SPK on DSM 7.1 on DS920+ (geminilake) fails

### ISSUE THREAD

**Issue by todrees1967** [runfalk/synology-wireguard#162]
**Description**
Trying to build the SPK on a DS920+ fails with some error messages while the build process.

**Steps to reproduce**
sudo docker run --rm --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.1 -v /volume1/docker/synowirespk71:/result_spk blackvoidclub/synobuild71

**Expected behavior**
Please see the following output with the error messages:
root@ZION:~# sudo docker run --rm --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.1 -v /volume1/docker/synowirespk71:/result_spk blackvoidclub/synobuild71
WireGuard version:        1.0.20220627
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.5

Cloning into 'pkgscripts-ng'...
[2022-07-26 10:30:36,167] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=base
[2022-07-26 10:30:51,928] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=geminilake
[2022-07-26 10:31:05,033] INFO: tar -xhf /toolkit_tarballs/base_env-7.1.txz -C /build_env/ds.geminilake-7.1
[2022-07-26 10:33:15,762] INFO: tar -xhf /toolkit_tarballs/ds.geminilake-7.1.env.txz -C /build_env/ds.geminilake-7.1
[2022-07-26 10:34:00,803] INFO: tar -xhf /toolkit_tarballs/ds.geminilake-7.1.dev.txz -C /build_env/ds.geminilake-7.1
[2022-07-26 10:34:56,729] INFO: All task finished.
--2022-07-26 10:34:57--  https://crt.sh/?d=8395
Resolving crt.sh (crt.sh)... 91.199.212.73, 2a0e:ac00:c7:d449::5bc7:d449
Connecting to crt.sh (crt.sh)|91.199.212.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1200 (1.2K) [application/pkix-cert]
Saving to: 'DSTRootCAX3_Extended.crt'

     0K .                                                     100% 1006M=0s

2022-07-26 10:34:57 (1006 MB/s) - 'DSTRootCAX3_Extended.crt' saved [1200/1200]

============================================================
                   Parse argument result                    
------------------------------------------------------------
platforms     : geminilake
env_section   : default
env_version   : 7.1
dep_level     : 1
parallel_proj : 1
branch        : master
suffix        : 
collect       : True
collecter     : True
link          : True
update_link   : False
build         : True
install       : True
only_install  : False
parallel      : 4
build_opt     : -J
install_opt   : 
print_log     : True
tee           : True
sdk_ver       : 6.2
package       : WireGuard

Processing [7.1-42784]: geminilake
============================================================
              Start to run "Traverse project"               
------------------------------------------------------------
Projects: WireGuard

============================================================
                Start to run "Link Project"                 
------------------------------------------------------------
Link /pkgscripts-ng -> /build_env/ds.geminilake-7.1/pkgscripts-ng
Link //source/WireGuard -> /build_env/ds.geminilake-7.1/source/WireGuard

============================================================
                Start to run "Build Package"                
------------------------------------------------------------
[geminilake] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.geminilake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.geminilake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "//pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "//pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.geminilake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.geminilake-7.1/logs.install: No such file or directory

root@ZION:~# 

**Synology NAS model**
DS920+

**Comment by kwr3017** [comment]
DS1019+
DSM 7.1-42661 Update 3

root@kwr3017:~# sudo docker run --rm --privileged --env PACKAGE_ARCH=apollolake --env DSM_VER=7.1 -v /volume1/docker/synowirespk71:/result_spk blackvoidclub/synobuild71
WireGuard version:        1.0.20220627
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.5

Cloning into 'pkgscripts-ng'...
[2022-07-29 09:15:26,199] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=base
[2022-07-29 09:15:48,407] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=apollolake
[2022-07-29 09:16:05,808] INFO: tar -xhf /toolkit_tarballs/base_env-7.1.txz -C /build_env/ds.apollolake-7.1
[2022-07-29 09:18:39,542] INFO: tar -xhf /toolkit_tarballs/ds.apollolake-7.1.env.txz -C /build_env/ds.apollolake-7.1
[2022-07-29 09:19:36,979] INFO: tar -xhf /toolkit_tarballs/ds.apollolake-7.1.dev.txz -C /build_env/ds.apollolake-7.1
[2022-07-29 09:20:41,171] INFO: All task finished.
--2022-07-29 09:20:41--  https://crt.sh/?d=8395
Resolving crt.sh (crt.sh)... 91.199.212.73, 2a0e:ac00:c7:d449::5bc7:d449
Connecting to crt.sh (crt.sh)|91.199.212.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1200 (1.2K) [application/pkix-cert]
Saving to: 'DSTRootCAX3_Extended.crt'

     0K .                                                     100%  653M=0s

2022-07-29 09:20:42 (653 MB/s) - 'DSTRootCAX3_Extended.crt' saved [1200/1200]

============================================================
                   Parse argument result
------------------------------------------------------------
platforms     : apollolake
env_section   : default
env_version   : 7.1
dep_level     : 1
parallel_proj : 1
branch        : master
suffix        :
collect       : True
collecter     : True
link          : True
update_link   : False
build         : True
install       : True
only_install  : False
parallel      : 4
build_opt     : -J
install_opt   :
print_log     : True
tee           : True
sdk_ver       : 6.2
package       : WireGuard

Processing [7.1-42784]: apollolake
============================================================
              Start to run "Traverse project"
------------------------------------------------------------
Projects: WireGuard

============================================================
                Start to run "Link Project"
------------------------------------------------------------
Link /pkgscripts-ng -> /build_env/ds.apollolake-7.1/pkgscripts-ng
Link //source/WireGuard -> /build_env/ds.apollolake-7.1/source/WireGuard


============================================================
                Start to run "Build Package"
------------------------------------------------------------
[apollolake] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --apollolake -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.apollolake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --apollolake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.apollolake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --apollolake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "//pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "//pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.apollolake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --apollolake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.apollolake-7.1/logs.install: No such file or directory

**Comment by vidalpascual** [comment]
Same error here with DS920+ and DSM 7.1-42661 Update 3

**Comment by ruimarinho** [comment]
Working fine here by applying patches as suggested on https://github.com/runfalk/synology-wireguard/issues/154#issuecomment-1169393940 and then:

```
docker run --privileged --env PACKAGE_ARCH=geminilake --env DSM_VER=7.1 -v $(pwd)/artifacts:/result_spk synobuild
```

Here are the compiled spk files if you need them (just renamed .spk.zip to .spk):

[WireGuard-geminilake-1.0.20220627_debug.spk.zip](https://github.com/runfalk/synology-wireguard/files/9266723/WireGuard-geminilake-1.0.20220627_debug.spk.zip)
[WireGuard-geminilake-1.0.20220627.spk.zip](https://github.com/runfalk/synology-wireguard/files/9266725/WireGuard-geminilake-1.0.20220627.spk.zip)

**Comment by paul-arthurthiery** [comment]
@ruimarinho tried to do the same on DS920+ with DSM 7.1-42661 Update 3 and I still hit the dreaded 
`/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied`
Also, you zip files appear to be empty, any way you could update those ? 🙏

**Comment by dtmichel** [comment]
Same issue here with DSM 7.1 on DS918+ (Apollolake).

**Comment by ruimarinho** [comment]
Here's what I'm using for `apollolake` and what I've compiled for `geminilake`. You need to rename these `.zip` files to `.spk` after downloading them.

`apollolake`:

[WireGuard-apollolake-1.0.20220627_debug.zip](https://github.com/runfalk/synology-wireguard/files/9794420/WireGuard-apollolake-1.0.20220627_debug.zip)
[WireGuard-apollolake-1.0.20220627.zip](https://github.com/runfalk/synology-wireguard/files/9794421/WireGuard-apollolake-1.0.20220627.zip)

`geminilake`:

[WireGuard-geminilake-1.0.20220627_debug.zip](https://github.com/runfalk/synology-wireguard/files/9794418/WireGuard-geminilake-1.0.20220627_debug.zip)
[WireGuard-geminilake-1.0.20220627.zip](https://github.com/runfalk/synology-wireguard/files/9794419/WireGuard-geminilake-1.0.20220627.zip)

**Comment by Starguts20** [comment]
i solved it by creating a virtual machine and installing ubuntu and docker on it. and then just run the command as if it were on the nas. You can then simply install the file that is created on the NAS. according to the guide. I hope this helps someone

**Comment by hmj78** [comment]
I managed to compile the SPK, but it will not run on my NAS(DS716+II)
[Braswell](https://madsen-jensen.dk/WireGuard-braswell-1.0.20220627.spk)

System failed to start [WireGuard]. it just says repair or stopped ???

**Comment by leandresz** [comment]
============================================================
                Start to run "Build Package"
------------------------------------------------------------
[geminilake] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.geminilake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.geminilake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "//pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "//pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.geminilake-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --geminilake -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.geminilake-7.1/logs.install: No such file or directory

**Comment by sebthom** [comment]
I configured a github action to build releases for all supported platforms. You can download the required SPK from here https://github.com/vegardit/synology-wireguard/releases

**Comment by GroteVriendelijkeReus** [comment]
docker run --rm --privileged --env PACKAGE_ARCH=v1000 --env DSM_VER=7.1 -v /volume1/docker/synowirespk71:/result_spk blackvoidclub/synobuild71
WireGuard version:        1.0.20220627
WireGuard tools version:  1.0.20210914
libmnl version:           1.0.5

Cloning into 'pkgscripts-ng'...
[2022-12-13 20:49:02,340] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=base
[2022-12-13 20:50:48,729] INFO: Download... https://dataupdate7.synology.com/toolchain/v1/get_download_list?identify=toolkit&version=7.1&platform=v1000
[2022-12-13 20:52:11,798] INFO: tar -xhf /toolkit_tarballs/base_env-7.1.txz -C /build_env/ds.v1000-7.1
[2022-12-13 20:54:23,832] INFO: tar -xhf /toolkit_tarballs/ds.v1000-7.1.env.txz -C /build_env/ds.v1000-7.1
[2022-12-13 20:55:16,533] INFO: tar -xhf /toolkit_tarballs/ds.v1000-7.1.dev.txz -C /build_env/ds.v1000-7.1
[2022-12-13 20:56:13,161] INFO: All task finished.
--2022-12-13 20:56:13--  https://crt.sh/?d=8395
Resolving crt.sh (crt.sh)... 91.199.212.73, 2a0e:ac00:c7:d449::5bc7:d449
Connecting to crt.sh (crt.sh)|91.199.212.73|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1200 (1.2K) [application/pkix-cert]
Saving to: 'DSTRootCAX3_Extended.crt'

     0K .                                                     100% 1004M=0s

2022-12-13 20:56:13 (1004 MB/s) - 'DSTRootCAX3_Extended.crt' saved [1200/1200]

============================================================
                   Parse argument result
------------------------------------------------------------
platforms     : v1000
env_section   : default
env_version   : 7.1
dep_level     : 1
parallel_proj : 1
branch        : master
suffix        :
collect       : True
collecter     : True
link          : True
update_link   : False
build         : True
install       : True
only_install  : False
parallel      : 8
build_opt     : -J
install_opt   :
print_log     : True
tee           : True
sdk_ver       : 6.2
package       : WireGuard

Processing [7.1-42784]: v1000
============================================================
              Start to run "Traverse project"
------------------------------------------------------------
Projects: WireGuard

============================================================
                Start to run "Link Project"
------------------------------------------------------------
Link /pkgscripts-ng -> /build_env/ds.v1000-7.1/pkgscripts-ng
Link //source/WireGuard -> /build_env/ds.v1000-7.1/source/WireGuard


============================================================
                Start to run "Build Package"
------------------------------------------------------------
[v1000] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --v1000 -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.v1000-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --v1000 -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.v1000-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --v1000 -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "//pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "//pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.v1000-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --v1000 -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.v1000-7.1/logs.install: No such file or directory

**Comment by GroteVriendelijkeReus** [comment]
> I configured a github action to build releases for all supported platforms. You can download the required SPK from here https://github.com/vegardit/synology-wireguard/releases

I couldn't find mine.  v1000.  Can you perhaps compile my version too?

**Comment by 1aranzant** [comment]
Same issue on DS416play, DSM 7.1   

Processing [7.1-42784]: braswell
============================================================
              Start to run "Traverse project"               
------------------------------------------------------------
Projects: WireGuard

============================================================
                Start to run "Link Project"                 
------------------------------------------------------------
Link /pkgscripts-ng -> /build_env/ds.braswell-7.1/pkgscripts-ng
Link //source/WireGuard -> /build_env/ds.braswell-7.1/source/WireGuard


============================================================
                Start to run "Build Package"                
------------------------------------------------------------
[braswell] env PackageName=WireGuard /pkgscripts-ng/SynoBuild --braswell -c --min-sdk 6.2 -J WireGuard
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.braswell-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --braswell -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "//pkgscripts-ng/include/python/exec_env.py", line 76, in execute
    output = commandrunner.run(cmd, display=display, **kwargs)
  File "//pkgscripts-ng/include/python/commandrunner.py", line 39, in run
    raise RunShellFailed(p.returncode, cmd, output)
commandrunner.RunShellFailed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "//pkgscripts-ng/include/python/parallel.py", line 15, in __call__
    result = self.__callable(*args, **kwargs)
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 191, in run_command
    env.execute(cmd, display=len(self.env_config.platforms)
  File "//pkgscripts-ng/include/python/exec_env.py", line 79, in execute
    raise EnvError(
exec_env.EnvError: ('Execute chroot /build_env/ds.braswell-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --braswell -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "//pkgscripts-ng/PkgCreate.py", line 184, in <module>
    main(sys.argv[1:])
  File "//pkgscripts-ng/PkgCreate.py", line 177, in main
    packer.pack_package()
  File "//pkgscripts-ng/include/python/pkguniform.py", line 437, in pack_package
    worker.execute()
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 86, in execute
    self._process_output(self._run(*argv))
  File "//pkgscripts-ng/include/python/pkgcommon.py", line 212, in _run
    return doPlatformParallel(self.run_command, self.env_config.platforms)
  File "//pkgscripts-ng/include/python/parallel.py", line 60, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.10/multiprocessing/pool.py", line 771, in get
    raise self._value
exec_env.EnvError: ('Execute chroot /build_env/ds.braswell-7.1 env PackageName=WireGuard /pkgscripts-ng/SynoBuild --braswell -c --min-sdk 6.2 -J WireGuard failed', '/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied\nERROR: This script must be run as root')
Build log
=========
/pkgscripts-ng/include/check: line 93: /dev/null: Permission denied
ERROR: This script must be run as root
Install log
===========
cat: /build_env/ds.braswell-7.1/logs.install: No such file or directory

**Comment by jack-bits** [comment]
Exact same error on DS920+ (geminilake), after upgrading to DSM 7.2-64570 Update 1.

This thread for DSM 7.1 is over 6 months old - is anyone looking at this issue?

**Comment by vidalpascual** [comment]
> Here's what I'm using for `apollolake` and what I've compiled for `geminilake`. You need to rename these `.zip` files to `.spk` after downloading them.
> 
> `apollolake`:
> 
> [WireGuard-apollolake-1.0.20220627_debug.zip](https://github.com/runfalk/synology-wireguard/files/9794420/WireGuard-apollolake-1.0.20220627_debug.zip) [WireGuard-apollolake-1.0.20220627.zip](https://github.com/runfalk/synology-wireguard/files/9794421/WireGuard-apollolake-1.0.20220627.zip)
> 
> `geminilake`:
> 
> [WireGuard-geminilake-1.0.20220627_debug.zip](https://github.com/runfalk/synology-wireguard/files/9794418/WireGuard-geminilake-1.0.20220627_debug.zip) [WireGuard-geminilake-1.0.20220627.zip](https://github.com/runfalk/synology-wireguard/files/9794419/WireGuard-geminilake-1.0.20220627.zip)

Can you compile WG for 7.2 on geminilake?

**Comment by jarama** [comment]
When following the guide from blackvoid.club, I also encountered the "line 93: /dev/null: Permission denied" issue. I ran the following on my Synology DS1513+ (cedarview):

sudo -i
sudo docker run --rm --privileged --env PACKAGE_ARCH=cedarview --env DSM_VER=7.1 -v /volume1/docker/synowirespk71:/result_spk blackvoidclub/synobuild71

Would someone perhaps by willing to compile this SPK for my system and share it?

**Comment by francois-dorin** [comment]
Well, I had the exact same error on a DS418play, but I found the root cause of this. 

In short: the filesystem on which the container is deployed has the nodev option. So, I had to remove it before successfully compiled the SPK.

In my case, the *problematic* filesystem was `/volume1/@docker/btrfs`

I just executed the following command:
```
mount -odev,remount /volume1/@docker/btrfs
```

then I ran the `docker run`command and the compilation worked perfectly and generated 2 spk (release and debug)
