### ISSUE TITLE
Issue compiling with Braswell architecture [DS216-II]

### ISSUE THREAD

**Issue by emrul** [runfalk/synology-wireguard#19]
I followed the docker instructions and received the following after a while.  Any points on what might be required to correct this? (FYI I had tried without HAS_MEMNEQ first but received the same output).

```
sudo docker run --rm --privileged --env PACKAGE_ARCH=braswell --env DSM_VER=6.2 --env HAS_MEMNEQ=1 -v $(pwd)/artifacts:/result_spk synobuild
Cloning into 'pkgscripts-ng'...
Download... https://sourceforge.net/projects/dsgpl/files/toolkit/DSM6.2/base_env-6.2.txz
Download destination: /toolkit_tarballs/base_env-6.2.txz%
Download... https://sourceforge.net/projects/dsgpl/files/toolkit/DSM6.2/ds.braswell-6.2.env.txz
Download destination: /toolkit_tarballs/ds.braswell-6.2.env.txz
Download... https://sourceforge.net/projects/dsgpl/files/toolkit/DSM6.2/ds.braswell-6.2.dev.txz
Download destination: /toolkit_tarballs/ds.braswell-6.2.dev.txz
tar: usr/lib/jvm/java-7-jdk/jre/lib/i386/client: Directory renamed before its status could be extracted
tar: usr/lib/jvm/java-7-jdk/jre/lib/i386/server: Directory renamed before its status could be extracted
tar: usr/lib/jvm/java-7-jdk/jre/lib/i386: Directory renamed before its status could be extracted
tar: usr/lib/jvm/java-7-jdk/jre/lib: Directory renamed before its status could be extracted
tar: usr/lib/jvm/java-7-jdk/jre: Directory renamed before its status could be extracted
tar: usr/lib/python3.4/config-3.4m: Directory renamed before its status could be extracted
tar: usr/lib/python3.4: Directory renamed before its status could be extracted
tar: usr/lib/firmware/libertas: Directory renamed before its status could be extracted
tar: usr/lib/firmware: Directory renamed before its status could be extracted
tar: usr/lib/python2.7/config: Directory renamed before its status could be extracted
tar: usr/lib/python2.7: Directory renamed before its status could be extracted
tar: usr/lib/ccache/bin: Directory renamed before its status could be extracted
tar: usr/lib/ccache: Directory renamed before its status could be extracted
tar: usr/lib/systemd/system/shutdown.target.wants: Directory renamed before its status could be extracted
tar: usr/lib/systemd/system/multi-user.target.wants: Directory renamed before its status could be extracted
tar: usr/lib/systemd/system: Directory renamed before its status could be extracted
tar: usr/lib/systemd: Directory renamed before its status could be extracted
tar: usr/lib/p11-kit: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/eslint/node_modules/acorn-jsx/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/eslint/node_modules/acorn-jsx/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/eslint/node_modules/acorn-jsx: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/eslint/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/eslint/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/eslint: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-loader/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-loader/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-loader: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/sass-loader/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/sass-loader/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/sass-loader: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/babel-loader/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/babel-loader/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/babel-loader: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-template-compiler/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-template-compiler/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-template-compiler: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/jslint/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/jslint/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/jslint: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/file-loader/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/file-loader/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/file-loader: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/css-loader/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/css-loader/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/css-loader: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/jshint/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/jshint/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/jshint: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/node-sass/node_modules/node-gyp/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/node-sass/node_modules/node-gyp/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/node-sass/node_modules/node-gyp: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/node-sass/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/node-sass/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/node-sass: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-style-loader/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-style-loader/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/vue-style-loader: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-dev-server/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-dev-server/node_modules/webpack-dev-middleware: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-dev-server/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-dev-server: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-cli/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-cli/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/webpack-cli: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/core/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/core/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/core: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/preset-env/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/preset-env/node_modules/regjsparser/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/preset-env/node_modules/regjsparser/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/preset-env/node_modules/regjsparser: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/preset-env/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/preset-env: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/cli/node_modules/.bin: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/cli/node_modules: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel/cli: Directory renamed before its status could be extracted
tar: usr/lib/node_modules/@babel: Directory renamed before its status could be extracted
tar: usr/lib/node_modules: Directory renamed before its status could be extracted
tar: usr/include/gdbm: Directory renamed before its status could be extracted
tar: usr/include: Directory renamed before its status could be extracted
tar: usr/local/share: Directory renamed before its status could be extracted
tar: usr/local/tool: Directory renamed before its status could be extracted
tar: usr/local: Directory renamed before its status could be extracted
tar: usr/share/man/man7: Directory renamed before its status could be extracted
tar: usr/share/man/man5: Directory renamed before its status could be extracted
tar: usr/share/man/man1: Directory renamed before its status could be extracted
tar: usr/share/man: Directory renamed before its status could be extracted
tar: usr/share/vim/vimfiles/help: Directory renamed before its status could be extracted
tar: usr/share/vim/vimfiles/syntax: Directory renamed before its status could be extracted
tar: usr/share/vim/vimfiles/indent: Directory renamed before its status could be extracted
tar: usr/share/vim/vimfiles: Directory renamed before its status could be extracted
tar: usr/share/vim: Directory renamed before its status could be extracted
tar: usr/share/licenses/eslint: Directory renamed before its status could be extracted
tar: usr/share/licenses/xz: Directory renamed before its status could be extracted
tar: usr/share/licenses/p7zip: Directory renamed before its status could be extracted
tar: usr/share/licenses/gcc-multilib: Directory renamed before its status could be extracted
tar: usr/share/licenses/vim-runtime: Directory renamed before its status could be extracted
tar: usr/share/licenses: Directory renamed before its status could be extracted
tar: usr/share/doc/xz: Directory renamed before its status could be extracted
tar: usr/share/doc: Directory renamed before its status could be extracted
tar: usr/share/apache-ant: Directory renamed before its status could be extracted
tar: usr/share/locale/gl/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/gl: Directory renamed before its status could be extracted
tar: usr/share/locale/lt/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/lt: Directory renamed before its status could be extracted
tar: usr/share/locale/eo/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/eo: Directory renamed before its status could be extracted
tar: usr/share/locale/sk/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/sk: Directory renamed before its status could be extracted
tar: usr/share/locale/tr/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/tr: Directory renamed before its status could be extracted
tar: usr/share/locale/sl/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/sl: Directory renamed before its status could be extracted
tar: usr/share/locale/fi/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/fi: Directory renamed before its status could be extracted
tar: usr/share/locale/zh_TW/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/zh_TW: Directory renamed before its status could be extracted
tar: usr/share/locale/uk/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/uk: Directory renamed before its status could be extracted
tar: usr/share/locale/et/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/et: Directory renamed before its status could be extracted
tar: usr/share/locale/pt_BR/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/pt_BR: Directory renamed before its status could be extracted
tar: usr/share/locale/el/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/el: Directory renamed before its status could be extracted
tar: usr/share/locale/ia/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ia: Directory renamed before its status could be extracted
tar: usr/share/locale/it/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/it: Directory renamed before its status could be extracted
tar: usr/share/locale/hr/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/hr: Directory renamed before its status could be extracted
tar: usr/share/locale/kk/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/kk: Directory renamed before its status could be extracted
tar: usr/share/locale/cs/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/cs: Directory renamed before its status could be extracted
tar: usr/share/locale/af/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/af: Directory renamed before its status could be extracted
tar: usr/share/locale/eu/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/eu: Directory renamed before its status could be extracted
tar: usr/share/locale/da/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/da: Directory renamed before its status could be extracted
tar: usr/share/locale/be/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/be: Directory renamed before its status could be extracted
tar: usr/share/locale/sv/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/sv: Directory renamed before its status could be extracted
tar: usr/share/locale/lg/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/lg: Directory renamed before its status could be extracted
tar: usr/share/locale/ko/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ko: Directory renamed before its status could be extracted
tar: usr/share/locale/pt/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/pt: Directory renamed before its status could be extracted
tar: usr/share/locale/ms/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ms: Directory renamed before its status could be extracted
tar: usr/share/locale/ja/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ja: Directory renamed before its status could be extracted
tar: usr/share/locale/ga/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ga: Directory renamed before its status could be extracted
tar: usr/share/locale/zh_CN/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/zh_CN: Directory renamed before its status could be extracted
tar: usr/share/locale/ru/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ru: Directory renamed before its status could be extracted
tar: usr/share/locale/nl/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/nl: Directory renamed before its status could be extracted
tar: usr/share/locale/fr/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/fr: Directory renamed before its status could be extracted
tar: usr/share/locale/vi/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/vi: Directory renamed before its status could be extracted
tar: usr/share/locale/pl/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/pl: Directory renamed before its status could be extracted
tar: usr/share/locale/es/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/es: Directory renamed before its status could be extracted
tar: usr/share/locale/de/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/de: Directory renamed before its status could be extracted
tar: usr/share/locale/ro/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ro: Directory renamed before its status could be extracted
tar: usr/share/locale/ca/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/ca: Directory renamed before its status could be extracted
tar: usr/share/locale/bg/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/bg: Directory renamed before its status could be extracted
tar: usr/share/locale/nb/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/nb: Directory renamed before its status could be extracted
tar: usr/share/locale/hu/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/hu: Directory renamed before its status could be extracted
tar: usr/share/locale/id/LC_TIME: Directory renamed before its status could be extracted
tar: usr/share/locale/id: Directory renamed before its status could be extracted
tar: usr/share/locale: Directory renamed before its status could be extracted
tar: usr/share/dict: Directory renamed before its status could be extracted
tar: usr/share: Directory renamed before its status could be extracted
tar: usr/lib32: Directory renamed before its status could be extracted
tar: root: Directory renamed before its status could be extracted
tar: etc: Directory renamed before its status could be extracted
tar: dev: Directory renamed before its status could be extracted
tar: Exiting with failure status due to previous errors
tar -xhf /toolkit_tarballs/base_env-6.2.txz -C /build_env/ds.braswell-6.2
Traceback (most recent call last):
  File "/pkgscripts-ng/include/python/parallel.py", line 12, in __call__
    result = self.__callable(*args, **kwargs)
  File "pkgscripts-ng/EnvDeploy", line 151, in deploy_base_env
    self.__extract__(base_tarball, BuildEnv.getChrootSynoBase(platform, self.version, self.suffix))
  File "pkgscripts-ng/EnvDeploy", line 147, in __extract__
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-6.2.txz', '-C', '/build_env/ds.braswell-6.2']' returned non-zero exit status 2.

multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/pkgscripts-ng/include/python/parallel.py", line 12, in __call__
    result = self.__callable(*args, **kwargs)
  File "pkgscripts-ng/EnvDeploy", line 151, in deploy_base_env
    self.__extract__(base_tarball, BuildEnv.getChrootSynoBase(platform, self.version, self.suffix))
  File "pkgscripts-ng/EnvDeploy", line 147, in __extract__
    subprocess.check_call(cmd)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-6.2.txz', '-C', '/build_env/ds.braswell-6.2']' returned non-zero exit status 2.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pkgscripts-ng/EnvDeploy", line 335, in <module>
    main(sys.argv[1:])
  File "pkgscripts-ng/EnvDeploy", line 329, in main
    ToolkitDeployer(args, platforms, tarball_manager).deploy()
  File "pkgscripts-ng/EnvDeploy", line 236, in deploy
    doPlatformParallel(self.deploy_base_env, self.platforms)
  File "/pkgscripts-ng/include/python/parallel.py", line 57, in doPlatformParallel
    output[item] = results[item].get()
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
subprocess.CalledProcessError: Command '['tar', '-xhf', '/toolkit_tarballs/base_env-6.2.txz', '-C', '/build_env/ds.braswell-6.2']' returned non-zero exit status 2.
```

**Comment by runfalk** [comment]
This looks really weird. This seems to happen before anything related to wireguard happens. The exception is within the python scripy provided by Synology. I think this may be a problem with Synology's pkgscripts-ng repository and maybe you should open a bug there.

Could you install the pkgscripts-ng environment in a container manually and see if you get the same error?

**Comment by fredrike** [comment]
I had the same issue (on Mac OS docker) so I built it directly on my DS716+II which worked fine.

**Comment by emrul** [comment]
@fredrike I can confirm building on the DS216 itself worked - so will go report the issue to Synology as that's likely where the issue comes from.
