### ISSUE TITLE
Compile fails on DS3615xs DSM 6.2.3

### ISSUE THREAD

**Issue by appleandcream** [runfalk/synology-wireguard#38]
**Description**
Trying to compile on DS3615xs but it fails to create the SPK-file

**Steps to reproduce**
1. Installed Docker and Git Server through the Synology GUI interface.
2. SSH to DS3615xs and run:
```
sudo -i
cd root
git clone https://github.com/runfalk/synology-wireguard.git
cd synology-wireguard/ 
docker build -t synobuild .
```
So far everything went fine. But when running the following:
```
docker run --rm --privileged --env PACKAGE_ARCH=bromolow --env DSM_VER=6.2 -v $(pwd):/result_spk synobuild
```
I get:
```
ult_spk synobuild
Cloning into 'pkgscripts-ng'...
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 724, in create_connection
    raise err
  File "/usr/lib/python3.6/socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [Errno 110] Connection timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pkgscripts-ng/EnvDeploy", line 335, in <module>
    main(sys.argv[1:])
  File "pkgscripts-ng/EnvDeploy", line 326, in main
    ToolkitDownloader(args.version, platforms, tarball_manager, args.quiet).download_toolkit()
  File "pkgscripts-ng/EnvDeploy", line 118, in download_toolkit
    if self._test_url_available(url):
  File "pkgscripts-ng/EnvDeploy", line 99, in _test_url_available
    return int(urllib.request.urlopen(url).getcode()) == 200
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 110] Connection timed out>
```

**Expected behavior**
SPK-file is not created in artifacts directory

**Synology NAS model**
DS3615xs

**wg0.conf**
```
haven't reached this far yet
```

**Comment by runfalk** [comment]
So I've had a lot of problems with the SDK downloads recently. I've basically needed to retry/wait for hours for it to complete. I've opened a ticket (https://github.com/SynologyOpenSource/pkgscripts-ng/issues/21) with Synology, but they haven't replied (and given their track record I don't think they will). I'm a bit weary about using the files suggested in the reply since the legality of them may be a bit questionable.

**Comment by appleandcream** [comment]
Efter several tries it finally compiled and I could add it to Package Center thought:
´´´
synopkg install WireGuard-bromolow-1.0.20200401.spk
´´´

Now to figure out WireGuard settings =)

**Comment by runfalk** [comment]
Glad to hear it worked. Sad that Synology is neglecting their own SDK.

I'll compile it myself and add it once you confirm that it actually runs :)

**Comment by pythonbobo** [comment]
It would be really nice if some of you could share the .spk for bromolow. I am running into the same downloading problems.

**Comment by runfalk** [comment]
Did it for you, let me know if it works.

[WireGuard-bromolow-1.0.20200401.zip](https://github.com/runfalk/synology-wireguard/files/4664809/WireGuard-bromolow-1.0.20200401.zip)

**Comment by runfalk** [comment]
Closing this, please reopen if the issue persists.
